services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: consultation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d consultation_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/consultation_db
      HF_HOME: /app/model_cache
    volumes:
      - ./backend/model_cache:/app/model_cache
      - ./backend:/app
    ports:
      - "18000:8000"
    deploy:
      resources:
        limits:
          memory: 4G

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:18000
    ports:
      - "13000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
