/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 텍스트 벡터 검색 시스템
 * 교사-학부모 정기상담 내용 벡터 검색 시스템
 * OpenAPI spec version: 1.0.0
 */
import type { ConsultationSearchRequestLimit } from './consultationSearchRequestLimit';
import type { ConsultationSearchRequestSkip } from './consultationSearchRequestSkip';
import type { ConsultationSearchRequestPage } from './consultationSearchRequestPage';
import type { ConsultationSearchRequestSimilarityThreshold } from './consultationSearchRequestSimilarityThreshold';

export interface ConsultationSearchRequest {
  query: string;
  limit?: ConsultationSearchRequestLimit;
  skip?: ConsultationSearchRequestSkip;
  page?: ConsultationSearchRequestPage;
  /** 유사도 임계값 (0.0-1.0) */
  similarity_threshold?: ConsultationSearchRequestSimilarityThreshold;
}
