/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * 텍스트 벡터 검색 시스템
 * 교사-학부모 정기상담 내용 벡터 검색 시스템
 * OpenAPI spec version: 1.0.0
 */

export * from './consultationCreate';
export * from './consultationResponse';
export * from './consultationSearchRequest';
export * from './consultationSearchRequestLimit';
export * from './consultationSearchRequestPage';
export * from './consultationSearchRequestSimilarityThreshold';
export * from './consultationSearchRequestSkip';
export * from './consultationSearchResponse';
export * from './consultationSearchResult';
export * from './consultationUpdate';
export * from './hTTPValidationError';
export * from './readConsultationsApiV1ConsultationsGetParams';
export * from './validationError';
export * from './validationErrorLocItem';